# Spotify API queries params
PAGE_SIZE = 50
MAX_OFFSET = 1000
MIN_DATE_DEFAULT = 1500
MAX_DATE_DEFAULT = 2100

# database params
MAX_TRACKS_PER_ARTIST = 25
ARTIST_POPULARITY_THRESHOLD = 50
TRACK_POPULARITY_THRESHOLD = 50
INTRA_ARTIST_POPULARITY_INDEX_THRESHOLD = 10
MAX_NUMBER_RELATED_ARTISTS = 10

# game params
STAGES_DURATION = [1, 2, 4, 7, 11, 16]
POINTS_EARNED_FOR_CORRECT_GUESS = [21, 15, 10, 6, 3, 1]
POINTS_LOST_FOR_INCORRECT_GUESS = 2
POINTS_EARNED_FOR_PERFECT_DATE = 3
POINTS_EARNED_FOR_CLOSE_DATE = 1
POINTS_LOST_FOR_BAD_DATE = 1
POINTS_EARNED_FOR_CORRECT_ALBUM = 3
POINTS_EARNED_FOR_INCORRECT_ALBUM = 1
GUESS_YEAR = True
GUESS_ALBUM = False
